### PR TITLE
Report which fields for selecting token were provided

### PR DESCRIPTION
**Pull request by cbroglie**
We automatically generate the `crypto11.Config` values from a PKCS #11
URI, so it's helpful to be report exactly which fields were provided.

### CODE REVIEW

**Comment by cbroglie** [comment]
If you don't want this in the library we can easily add the same logic to our code before calling `Configure`, let me know.

**Comment by dmjones** [comment]
Thanks for the PR. Always happy to improve the quality of our error messages. The PR is currently failing due to some tests which relied on the old error messages - would you mind patching that up so I can merge?

That being said, I'm concerned we might break your code (or user experience) one day by changing our error handling. I've tried to avoid the errors becoming part of the API, hence why none of them are exported in v1.0.0.

Even if we merge this in, your code may want to do an equivalent check itself. Especially if you were thinking of piping our error messages to your users.

**Comment by cbroglie** [comment]
I fixed the tests, but no hard feelings if you don't want to merge it. You're right that we should also have this logic on our end.

**Review by dmjones — APPROVED** [review]
LGTM

**Comment by dmjones** [comment]
Now available in https://github.com/ThalesIgnite/crypto11/releases/tag/v1.0.1.

**Pull request merged**
