### PR TITLE
allow uninitialization of lib handle

### PR DESCRIPTION
**Pull request by sitano**
```
func Close() error
```

to allow releasing of the default library handle

### CODE REVIEW

**Comment by optnfast** [comment]
Thankyou for the PR. This needs a bit more before we can merge it.

1. Following [PR2](https://github.com/ThalesIgnite/crypto11/pull/3), I think it should use `(*ResourcePool)Close` to close each slot's sessions (replacing `CloseSessions`).
2. It needs documentation comments on each public method. See https://blog.golang.org/godoc-documenting-go-code for a style guide.
3. If you use `ResetLibHandle` but not `Finalize`, I think the system  will be left in an inconsistent state, with a pool of session handles that don't belong to a future value of `libHandle`. So we need some strategy for preventing this situation, for instance having `ResetLibHandle` call `Finalize` first.

**Comment by sitano** [comment]
@nfewx I've refactored code based on your comments and mentioned PR #3. 

I've created a new type `sessionPool` which secures a `resourcePool` with a `RWMutex`. The whole sessions pool made independent of the library singleton libHandle. I've added few helpers.

As the `PKCS11Session` type is public and can be created by any context, and the sessions pool is indepented of any specific context, and the session wrapper it self is kind of independent of the pool, I've placed `Ctx *pkcs.Ctx` into the session type, so it can implement `Close()`.

**Comment by sitano** [comment]
I have removed `vitess` dependency and move resource pool implementation to this code base.

**Comment by optnfast** [comment]
I appreciate the desire to minimize dependencies but I'd rather keep that code as an external dependency, partly for licensing reasons and partly to simplify tracking of any upstream changes.

**Comment by sitano** [comment]
@nfewx ok. what do you think of new `PKCS11Session` struct? does it fit your expectations on design? another way was to put `ctx` object into the sessions pool object, but I was not sure whether the pool would be used across multiple contexts in the future i.e.

**Comment by sitano** [comment]
from another point of view, there is an API which recv handles which could be created with different session context (not libHandle) and then having it at hand allows passing of the right session handle to the pkcs11 calls.

**Comment by optnfast** [comment]
I like the design as of 4b969bb6bee6601462ed15528fafdef9d8b8c2a8. Anyone else want to chip in before I merge? (@solcates?)

**Pull request merged**
