### PR TITLE
Added id and label key generators

### PR DESCRIPTION
**Pull request by bernard-wagner**
Partially implements #15

### CODE REVIEW

**Review by nickrmc83 — CHANGES_REQUESTED** [review]
@bernard-wagner can you add or update appropriate test cases to exercise the new public API functions?

**Comment by dmjones** [comment]
Hi @bernard-wagner. Thank you for taking the time to share your pull request.

As you may have just seen in #15, the future of key generation in the library is in question. If you would like to join that discussion, please do. Unless we change our minds on that point, I can't see us merging this particular PR.

**Comment by bernard-wagner** [comment]
> @bernard-wagner can you add or update appropriate test cases to exercise the new public API functions?

Any guidance on how to structure these tests without duplicating all the existing tests, as the same code paths will be covered 99% of the time?

**Comment by dmjones** [comment]
Closing this PR, per my comment above (https://github.com/ThalesIgnite/crypto11/pull/22#issuecomment-454391162).

**Pull request closed without merging**
