### PR TITLE
Add a method to delete a certificate.

### PR DESCRIPTION
**Pull request by maraino**
### Description

This PR adds a new method to delete a previously imported certificate:

```go
func (c *Context) DeleteCertificate(id []byte, label []byte, serial *big.Int) error
```

### CODE REVIEW

**Comment by maraino** [comment]
If the PR is approved and merged, a new release will be appreciated.

**Comment by maraino** [comment]
@ProsaicSatsuma Any update on this?

**Review by ProsaicSatsuma — APPROVED** [review]
Looks good to me

**Comment by ProsaicSatsuma** [comment]
Apologies for the delay - missed the earlier notifications. Thanks for the PR. Looks good. Approved

**Comment by maraino** [comment]
@ProsaicSatsuma Can you tag a new release?

**Comment by ProsaicSatsuma** [comment]
done. Tagged as v1.2.4

**Pull request merged**
